# Generated by Django 4.2.5 on 2026-02-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_comment_is_deleted_post_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentPost',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contents.post',),
        ),
    ]
