# Generated by Django 4.2.5 on 2026-02-05 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_recentpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotePost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contents.post')),
                ('quote', models.URLField()),
            ],
            options={
                'abstract': False,
            },
            bases=('contents.post',),
        ),
    ]
