services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["python3", "manage.py", "migrate"]

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: X
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
